<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Bienvenido al<br>Taller Práctico de Dockerización de Aplicaciones</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank">Laminas MVC Skeleton</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://media1.giphy.com/media/xUA7aZGnOPdTPpbkU8/giphy.gif?cid=790b7611135ddecfd17a9686be7d03dd33412c57231361fd&rid=giphy.gif&ct=g" target="_blank">
        La Resistencia es Fútil &raquo;
    </a>
</div>
<div class="row">
    <div class="col-md-4">
        <div style="width:100%;height:0;padding-bottom:76%;position:relative;"><iframe src="https://giphy.com/embed/x7gybOmE9zBmw" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/cat-star-trek-spock-x7gybOmE9zBmw"></a></p>
    </div>
    <div class="col-md-4">
        <div style="width:100%;height:0;padding-bottom:84%;position:relative;"><iframe src="https://giphy.com/embed/V6J9e90If8YyA" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/star-trek-borg-cats-V6J9e90If8YyA"></a></p>
    </div>
    <div class="col-md-4">
        <div style="width:100%;height:0;padding-bottom:49%;position:relative;"><iframe src="https://giphy.com/embed/gzXTuaCKrCZyXzkKKj" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/CBSAllAccess-star-trek-discovery-gzXTuaCKrCZyXzkKKj"></a></p>
    </div>
</div>


<div class="card-deck">
    <div class="card">
        <h3 class="card-header">Larga y próspera vida</h3>
        <div class="card-body">
            <p>
                Laminas Project is under active development. If you are
                interested in following the development, you can check
                <a href="https://media3.giphy.com/media/2EzVNMLqpNVn2/200w.webp?cid=ecf05e47o1261vqd5tu8z8c4q2qup8bkl6p7ysc9yh3keu6c&rid=200w.webp&ct=g">Laminas dev blog</a>,
                and <a href="https://media3.giphy.com/media/2EzVNMLqpNVn2/200w.webp?cid=ecf05e47o1261vqd5tu8z8c4q2qup8bkl6p7ysc9yh3keu6c&rid=200w.webp&ct=g">Laminas issue tracker</a>
                (link requires a GitHub account). This is a great resource
                for staying up to date with the latest developments!
            </p>

            <a class="btn btn-primary" href="https://media3.giphy.com/media/2EzVNMLqpNVn2/200w.webp?cid=ecf05e47o1261vqd5tu8z8c4q2qup8bkl6p7ysc9yh3keu6c&rid=200w.webp&ct=g" target="_blank">Laminas Project Portal &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h3 class="card-header">Star Trek</h3>
        <div class="card-body">
            <p>
                Laminas MVC is a modular application.
                You can find multiple compatible modules on packagist.
            </p>

            <a class="btn btn-primary" href="https://media1.giphy.com/media/l2SqhJ2Cj91fh8Kvm/giphy.gif?cid=ecf05e479veuil099z0kw8ko8j0aj2hjdn6g44bn8p1fcp2q&rid=giphy.gif&ct=g" target="_blank">
                Explore Laminas Modules &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h3 class="card-header">Pregúntale a Data</h3>
        <div class="card-body">
            <p>
                If you need any help or support while developing with Laminas,
                you may reach us via <a href="https://media4.giphy.com/media/l4FGzT4Y4o3gzANPi/giphy.gif?cid=ecf05e47cho82l5708u5rk3kzpkcqq7ta0ie30rz4z8xzqhw&rid=giphy.gif&ct=g">chat</a> or
                <a href="https://media4.giphy.com/media/l4FGzT4Y4o3gzANPi/giphy.gif?cid=ecf05e47cho82l5708u5rk3kzpkcqq7ta0ie30rz4z8xzqhw&rid=giphy.gif&ct=g">forum</a>.
                We'd love to hear any questions or feedback you may have
                regarding any release.
            </p>

            <a class="btn btn-primary" href="https://media4.giphy.com/media/l4FGzT4Y4o3gzANPi/giphy.gif?cid=ecf05e47cho82l5708u5rk3kzpkcqq7ta0ie30rz4z8xzqhw&rid=giphy.gif&ct=g" target="_blank">Ping us on chat &raquo;</a>
        </div>
    </div>
</div>
